<?php

return [
    [
        'id' => 1,
        'name' => 'Admin Biro Kesekretariatan',
        'email' => 'kestari.pusat@alfathunitel.org',
        'password' => '$2y$10$zrbE0QAeMUlkALlmd0DdTOewRfICMfbPvjfAk1FtSgSDDbxS3wq3m',
        'role' => 'superadmin',
        'unit' => 'Biro Kesekretariatan',
        'color_code' => 'red',
    ],
    [
        'id' => 2,
        'name' => 'Admin Biro Keuangan',
        'email' => 'keuangan.pusat@alfathunitel.org',
        'password' => '$2y$10$vAoHpEaVLOQx5NXlEkpYGum5fH7K3dkgnQHFvC2dM6KiJHM0LMEUO',
        'role' => 'admin',
        'unit' => 'Biro Keuangan',
        'color_code' => 'red',
    ],
    [
        'id' => 3,
        'name' => 'Admin Departemen Syiar Pusat',
        'email' => 'syiar.pusat@alfathunitel.org',
        'password' => '$2y$10$hIdEOXd4H04Y9zYHxa8JuOqjnCnderPwEzWEWJvaSzm0VI.jfEaBi',
        'role' => 'admin',
        'unit' => 'Departemen Syiar Pusat',
        'color_code' => 'red',
    ],
    [
        'id' => 4,
        'name' => 'Admin Departemen Kaderisasi Pusat',
        'email' => 'kaderisasi.pusat@alfathunitel.org',
        'password' => '$2y$10$1MQBDx6PELqPC9ovTFXy5O6dDsJs8Z7yO82c7c2E9CclyXz3.E0Yu',
        'role' => 'admin',
        'unit' => 'Departemen Kaderisasi Pusat',
        'color_code' => 'red',
    ],
    [
        'id' => 5,
        'name' => 'Admin Departemen MedKomInfo',
        'email' => 'medkom.pusat@alfathunitel.org',
        'password' => '$2y$10$2MS3m2tanKSoUwuIZclUAuUWaKqqbfdHh85nAjUUt3cyqUJgX01Qa',
        'role' => 'admin',
        'unit' => 'Departemen MedKomInfo',
        'color_code' => 'red',
    ],
    [
        'id' => 6,
        'name' => 'Admin LDF FIF',
        'email' => 'fif.fakultas@alfathunitel.org',
        'password' => '$2y$10$RidsLuJDJ4s8.hWQHnCHCuTKfmI2YGVbcVdd77070bzqPjbO9fRqe',
        'role' => 'admin',
        'unit' => 'LDF Al-Fath Fakultas Informatika',
        'color_code' => 'yellow',
    ],
    [
        'id' => 7,
        'name' => 'Admin LDF FTE',
        'email' => 'fte.fakultas@alfathunitel.org',
        'password' => '$2y$10$XxEHZEbacDjX6KFA.tGTpecK9CyV8QrcD1Rx9Z5dsxPgD3ZwahfTa',
        'role' => 'admin',
        'unit' => 'LDF Al-Fath Fakultas Teknik Elektro',
        'color_code' => 'blue_dark',
    ],
    [
        'id' => 8,
        'name' => 'Admin LDF FIK',
        'email' => 'fik.fakultas@alfathunitel.org',
        'password' => '$2y$10$i8igljAHX0gyw1IdVfiwwOWw82TdsX/IzpJS2JgRhQtWo4Wh9xquC',
        'role' => 'admin',
        'unit' => 'LDF Al-Fath Fakultas Industri Kreatif',
        'color_code' => 'orange',
    ],
    [
        'id' => 9,
        'name' => 'Admin LDF FIT',
        'email' => 'fit.fakultas@alfathunitel.org',
        'password' => '$2y$10$PXf4EtlYNcO1U/RHZSdKxOxIJg6krZqHmdk8BgDATfPRuBRQph06W',
        'role' => 'admin',
        'unit' => 'LDF Al-Fath Fakultas Ilmu Terapan',
        'color_code' => 'green_light',
    ],
    [
        'id' => 10,
        'name' => 'Admin LDF FKS',
        'email' => 'fks.fakultas@alfathunitel.org',
        'password' => '$2y$10$60N/jK4JN1pD4rU3Kuh.r.ZIQSXYnmbR6.qOl.zVR11zLYCdFALJm',
        'role' => 'admin',
        'unit' => 'LDF Al-Fath Fakultas Komunikasi dan Ilmu Sosial',
        'color_code' => 'purple',
    ],
    [
        'id' => 11,
        'name' => 'Admin LDF FRI',
        'email' => 'fri.fakultas@alfathunitel.org',
        'password' => '$2y$10$IcZacD..XojOfk0cuhcOruMmeQAIaEZhR8c5/i4fmMzlTMib9JyE.',
        'role' => 'admin',
        'unit' => 'LDF Al-Fath Fakultas Rekayasa Industri',
        'color_code' => 'green_dark',
    ],
    [
        'id' => 12,
        'name' => 'Admin LDF FEB',
        'email' => 'feb.fakultas@alfathunitel.org',
        'password' => '$2y$10$ujGcoxBeS9bZ5m3z/HSyK.dzH3m56EsVd9EDvoFNDtF.GoZgzP/EG',
        'role' => 'admin',
        'unit' => 'LDF Al-Fath Fakultas Ekonomi dan Bisnis',
        'color_code' => 'blue_light',
    ],
];
